global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /actuator/prometheus

    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']